[project]
name = "camera_calibration"
version = "0.1.0"
description = "runs end-to-end camera calibration"
readme = "README.md"
authors = [
    { name = "Tilman Burghoff", email = "t.burghoff@campus.tu-berlin.de" }
]
requires-python = ">=3.10"
dependencies = [
    "robotic>=0.3.5",
    "numpy >= 2.0.0",
    "opencv-python >= 4.7.0",
    "h5py",
]

[project.scripts]
camera_calibration = "camera_calibration.cli:cli"

[build-system]
requires = [
  "scikit-build-core",
    "robotic>=0.3.5",
    "numpy >= 2.0.0"
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
wheel.packages = ["camera_calibration"]

[tool.scikit-build.cmake]
source-dir = "camera_calibration/komo-aruco-calibration"
verbose = true
minimum-version = "3.15"
